# Generated by Django 5.0.6 on 2024-06-30 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebank', '0007_auto_20230406_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.CharField(default=datetime.datetime(2024, 6, 30, 17, 52, 38, 717409, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
