# Generated by Django 5.0.6 on 2024-06-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebank', '0009_rename_amount_transaction_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
