# Generated by Django 5.0.6 on 2024-06-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebank', '0011_alter_transaction_credit_alter_transaction_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
