# Generated by Django 5.0.6 on 2024-07-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebank', '0012_alter_transaction_credit_alter_transaction_debit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.CharField(max_length=100),
        ),
    ]
